//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MyCarApp.DAL.Database
{
    using System;
    using System.Collections.Generic;
    
    public partial class Car
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Car()
        {
            this.CarCategoryMappers = new HashSet<CarCategoryMapper>();
            this.CarVarients = new HashSet<CarVarient>();
            this.Reviews = new HashSet<Review>();
        }
    
        public string Name { get; set; }
        public string ShortDescription { get; set; }
        public string LongDescription { get; set; }
        public Nullable<System.DateTime> CreatedAt { get; set; }
        public Nullable<System.DateTime> ModifyAt { get; set; }
        public Nullable<System.Guid> CreaatedBy { get; set; }
        public Nullable<System.Guid> ModifiedBy { get; set; }
        public System.Guid Id { get; set; }
        public bool Status { get; set; }
        public bool IsDeleted { get; set; }
        public Nullable<System.Guid> CarCategoryId { get; set; }
        public string Brand { get; set; }
        public string Image { get; set; }
        public Nullable<System.Guid> AddressId { get; set; }
        public Nullable<decimal> Kilometers { get; set; }
    
        public virtual Address Address { get; set; }
        public virtual CarCategory CarCategory { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<CarCategoryMapper> CarCategoryMappers { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<CarVarient> CarVarients { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Review> Reviews { get; set; }
    }
}
