//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MyCarApp.DAL.Database
{
    using System;
    using System.Collections.Generic;
    
    public partial class CarCategoryMapper
    {
        public System.Guid Id { get; set; }
        public System.Guid CarId { get; set; }
        public System.Guid CarCategoryId { get; set; }
    
        public virtual CarCategory CarCategory { get; set; }
        public virtual Car Car { get; set; }
    }
}
