//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MyCarApp.DAL.Database
{
    using System;
    using System.Collections.Generic;
    
    public partial class Review
    {
        public System.Guid ReviewId { get; set; }
        public System.Guid CarId { get; set; }
        public Nullable<System.Guid> UserId { get; set; }
        public string Title { get; set; }
        public int Rating { get; set; }
        public string Discription { get; set; }
        public System.DateTime CreatedAt { get; set; }
        public Nullable<System.Guid> CreatedBy { get; set; }
        public string ModifiedAt { get; set; }
        public Nullable<System.Guid> ModifiedBy { get; set; }
        public bool IsDeleted { get; set; }
        public bool Status { get; set; }
    
        public virtual Car Car { get; set; }
        public virtual User User { get; set; }
    }
}
